version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps'
    cooldown:
      default-days: 7
    groups:
      actions:
        applies-to: version-updates
        update-types:
          - minor
          - patch

  - package-ecosystem: mix
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'deps'
    cooldown:
      default-days: 7
    groups:
      mix:
        applies-to: version-updates
        update-types:
          - minor
          - patch
