name: Dependabot auto-merge

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-automerge:
    runs-on: ubuntu-latest

    steps:
      - uses: KineticCafe/actions/dependabot-automerge@v1.0
        with:
          update-type: minor
