name: Dependabot auto-merge

on:
  pull_request:

permissions: {}

jobs:
  dependabot-automerge:
    name: Dependabot Auto-merge
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden the runner
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: block
          disable-sudo: true
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - uses: KineticCafe/actions/dependabot-automerge@49ed4df56156946c36e092976e44aac053423eca # v2.0.2
        with:
          update-type: minor
